services:
  mintpy-isce2:
    build:
      context: .
      dockerfile: Dockerfile
    image: mintpy-isce2:cf
    working_dir: /work
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Tokyo
      - EARTHDATA_USER=${EARTHDATA_USER}
      - EARTHDATA_PASS=${EARTHDATA_PASS}
    volumes:
      - ../workdir:/work
      - /mnt/myssd/masters/Jakarta:/mnt/ssd
      - ./init.sh:/usr/local/bin/init.sh:ro
    entrypoint: ["/usr/bin/tini", "--"]
    command: ["bash", "-lc", "source /usr/local/bin/init.sh"]

